# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/node:10.16.3
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: mathnavdb_test
          MYSQL_USER: ci_tester
          MYSQL_PASSWORD: test

    working_directory: /go/src/github.com/ahsu1230/mathnavigatorSite
    steps:
      - checkout
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client

      - run: go get -v -t -d ./...
      - run:
          name: Format Go codebase
          command: ./orion/formatter.sh
      - run:
          name: Run Go tests
          command: |
            go vet ./...
            go test -v ./...

      - run: cd sites/admin
      - run:
          name: Update npm
          command: npm update
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Format Javascript
          command: prettier --check "**/*.js"
