# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: mathnavdb_test
          MYSQL_USER: admin
          MYSQL_PASSWORD:

    working_directory: /go/src/github.com/ahsu1230/mathnavigatorSite
    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI;
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u admin -p --execute="SHOW DATABASES;"

      - run: cd orion
      - run: go get -v -t -d ./...
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...
