# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      # - image: circleci/mysql:8.0
      #   environment:
      #     MYSQL_ROOT_USER: root
      #     MYSQL_ROOT_PASSWORD: password
      #     MYSQL_HOST: 127.0.0.1
      #     MYSQL_PORT: 3308
      #     MYSQL_DATABASE: mathnavdb_test

    working_directory: /go/src/github.com/ahsu1230/mathnavigatorSite
    steps:
      - checkout
      # - run:
      #     name: Install MySQL CLI
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install default-mysql-client
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Start all containers
          command: |
            set -x
            docker-compose up -f constellations/docker-compose.yml -d

      - run: go get -v -t -d ./...
      - run:
          name: Format Go codebase
          command: ./constellations/go_formatter.sh .
      - run:
          name: Verify Go Modules
          command: |
            cd orion
            go mod verify
      - run:
          name: Run Orion Go tests
          command: |
            go vet ./...
            go test -v ./...
      - run:
          name: Install npm
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt install nodejs
            nodejs --version
            npm --version
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Check Javascript Format
          command: |
            sudo npm install -g prettier
            prettier --check "constellations/gemini" --config "constellations/gemini/.prettierrc.yml"
      - run:
          name: Run Gemini-Admin Enzyme React tests
          command: |
            cd constellations/gemini/admin
            npm install
            npm run test
      - run:
          name: Run Gemini-User Enzyme React tests
          command: |
            cd constellations/gemini/user
            npm install
            npm run test
