# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: mathnavdb_test
          MYSQL_USER: admin
          MYSQL_PASSWORD: password

    working_directory: /go/src/github.com/ahsu1230/mathnavigatorSite
    steps:
      - checkout
      - run:
          name: Install MySQL CLI;
          command: |
            sudo apt-get -y install default-mysql-client

      - run: cd orion
      - run: go get -v -t -d ./...
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...
